"""initalize database schema

Revision ID: fe2e9c686491
Revises:
Create Date: 2026-02-01 20:10:47.415669

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fe2e9c686491"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alias",
        sa.Column("telegram_user_id", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("telegram_user_id"),
    )
    op.create_table(
        "counselors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("telegram_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_alias", sa.String(), nullable=True),
        sa.Column("counselor_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("user_group_link", sa.String(), nullable=True),
        sa.Column("counselor_group_id", sa.Integer(), nullable=True),
        sa.Column("user_group_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["counselor_id"],
            ["counselors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("ADMIN", "SUPER_ADMIN", "SERVICE", name="user_role"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("groups")
    op.drop_table("counselors")
    op.drop_table("alias")
    op.drop_table("account")
    # ### end Alembic commands ###
